[window]
padding = { x = 2, y = 2 }
dynamic_padding = true

[scrolling]
history = 2000

[font]
normal = { family = "firacodenerdfont", style = "regular" }
size = 12.0

[colors.primary]
background = '0x1f2329'  # Darker background (bg0)
foreground = '0xa0a8b7'  # Light text (fg)

[colors.normal]
black   = '0x0e1013'  # Dark black (black)
red     = '0xe55561'  # Red color (red)
green   = '0x8ebd6b'  # Green color (green)
yellow  = '0xe2b86b'  # Yellow color (yellow)
blue    = '0x4fa6ed'  # Blue color (blue)
magenta = '0xbf68d9'  # Purple color (purple)
cyan    = '0x48b0bd'  # Cyan color (cyan)
white   = '0xa0a8b7'  # Light white (fg)

[colors.bright]
black   = '0x535965'  # Dark gray (grey)
red     = '0xe55561'  # Red color (same as normal red)
green   = '0x8ebd6b'  # Green color (same as normal green)
yellow  = '0xe2b86b'  # Yellow color (same as normal yellow)
blue    = '0x4fa6ed'  # Blue color (same as normal blue)
magenta = '0xbf68d9'  # Purple color (same as normal purple)
cyan    = '0x48b0bd'  # Cyan color (same as normal cyan)
white   = '0xa0a8b7'  # Light white (same as normal white)

[cursor]
style = { shape = "Block", blinking = "Off" }

[keyboard]
bindings = [{key = "X", mods = "Control | Shift", chars = "\u2660"}]
